### ISSUE TITLE
Missing gem dependencies - slop and backports

### ISSUE THREAD

**Issue by andrykonchin** [kkuprikov/forspell#7]
I encountered an issue with the latest 0.0.2 release.

```shell
$> forspell
Traceback (most recent call last):
	6: from /Users/aaz/.rbenv/versions/2.6.1/bin/forspell:23:in `<main>'
	5: from /Users/aaz/.rbenv/versions/2.6.1/bin/forspell:23:in `load'
	4: from /Users/aaz/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/forspell-0.0.2/exe/forspell:2:in `<top (required)>'
	3: from /Users/aaz/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/forspell-0.0.2/exe/forspell:2:in `require_relative'
	2: from /Users/aaz/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/forspell-0.0.2/lib/forspell/cli.rb:3:in `<top (required)>'
	1: from /Users/aaz/.rbenv/versions/2.6.1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/aaz/.rbenv/versions/2.6.1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- slop (LoadError)
```

Looks like both `slop` and `backports` gems should be declared in gemspec file:
https://github.com/kkuprikov/forspell/blob/master/lib/forspell/cli.rb#L3-L4

**Comment by kkuprikov** [comment]
Thanks for pointing this out, I've added dependencies in '0.0.3'

**Comment by andrykonchin** [comment]
It seems `kramdown` and `kramdown-parser-gfm` should be added as well.

**Comment by kkuprikov** [comment]
@andrykonchin thanks again, I've dealt with rest of dependencies in `0.0.4`. Should've checked first with a clean ruby installation.
